### ISSUE TITLE
Missing child_process dependency

### ISSUE THREAD

**Issue by equinusocio** [jonathantneal/watch-os-color-scheme#1]
Hi man, I get this error after installing it on node `v8.12.0` and `v10.12.0`:

```sh
This dependency was not found:

* child_process in ./node_modules/watch-os-color-scheme/index.js

To install it, you can run: npm install --save child_process
```

Same thing if i try to manually install `child_process` (which is an empty package)

**Comment by jonathantneal** [comment]
This is a very interesting bug, because `child_process` ships with Node.

https://nodejs.org/api/child_process.html#child_process_child_process

I’m very interested in knowing how you could be experiencing this issue.

**Comment by equinusocio** [comment]
I'm using node installed through brew and this is the first time i see this error. It sound really weird, i will try on another machine but i think my brew/node installation is just a bit messed up.

**Comment by equinusocio** [comment]
@jonathantneal The only "similar" issue i found is this and it seems to be related to webpack?

https://github.com/stripe/stripe-node/issues/265

**Comment by jonathantneal** [comment]
Would you let me know if that resolves your issue? I’m not sure if `child_process` should _ever_ be missing from Node. Are you trying to run this from within a browser, where perhaps the dependency cannot be used?

**Comment by equinusocio** [comment]
@jonathantneal Yes, I will let you know when i have time to try at home, i hope soon.

Meanwhile i tried to import and log `const { execSync } = require('child_process');` on another machine at work inside a react/ts project (brew installed node 10) and everything works. So i think we have 2 possibilities here:

- My brew/node for some reason is messed up
- Vue/Nuxt doesn't like `child_process` (wut?) 

I don't think mac os Mojave can be a problem here.

**Comment by equinusocio** [comment]
@jonathantneal I tried on my other machine and i get the same error. I really don't know what to do mmm

**Comment by jonathantneal** [comment]
Can you spin up a project to reproduce this?

**Comment by equinusocio** [comment]
@jonathantneal I tried with a vue project on codesandbox.io and everything works. So i think there is something wrong with the node package installed through homebrew.

If you want, you can make a try by cloning my project branch:
https://github.com/equinusocio/equinusocio.github.io/tree/test-cp

`npm i` then `npm run dev`

You will find this inside **pages/index.vue**:

```js
  methods: {
    stop: () => {
      watchOsColorScheme(prefersColorScheme => {
        console.log({ prefersColorScheme });
      });
    }
  },
  mounted () {
    this.stop()
  }
```

**Comment by jonathantneal** [comment]
> If you want, you can make a try by cloning my project branch

Ah, that’s it. This is being used on the web.

> Are you trying to run this from within a browser, where perhaps the dependency cannot be used?

You are trying to run this within a browser. That’s not possible. This could only work within Node.js apps.

**Comment by equinusocio** [comment]
Yeah, so i need to wait the w3 specs and implementations :) Thank you.

**Comment by equinusocio** [comment]
@jonathantneal Just a question, why it works on codesanbox.io?
