### ISSUE TITLE
Question on light scheme

### ISSUE THREAD

**Issue by equinusocio** [jonathantneal/watch-os-color-scheme#2]
Hi @jonathantneal, i tried to run in terminal `defaults read -g AppleInterfaceStyle` with default mac os style (not dark) and it returned this message:

```sh
2018-10-15 17:13:03.284 defaults[90044:8221685]
The domain/default pair of (kCFPreferencesAnyApplication, AppleInterfaceStyle) does not exist
```

If i enable the dark mode it return `dark`, so i guess there will not ever a `light` scheme returned (at least not on mac). Is this correct?

**Comment by jonathantneal** [comment]
@equinusocio, yes, that’s exactly right, and I handle this in the app very specifically.

https://github.com/jonathantneal/watch-os-color-scheme/blob/master/index.js#L10-L18

Since this isn’t a bug with my specific application, I’m closing this, but I’m absolutely fine continuing the discovery for your own discovery sake. Thanks for asking! :)

**Comment by equinusocio** [comment]
Ahm ok, so you are forcing `light`, that's make sense. Thank you for the reply and yes feel free to close this, i was curious about how you handled this case 👍🏻. Now i just need to know how to fix my other issue :D

**Comment by jonathantneal** [comment]
Yes, though to be clear, I’m not entirely forcing `light`, as I’m vetting a very specific error associated with `light`. Does that make sense?

**Comment by equinusocio** [comment]
Yes i think this make sense right now, until Apple will add another theme 🗡 or set `AppleInterfaceStyle` with a default value.

**Comment by jonathantneal** [comment]
I hope that scenario will be covered by https://github.com/jonathantneal/watch-os-color-scheme/blob/master/index.js#L12

By the way, the reason it crashes is because this key was added (and works) in older versions of MacOS, where the variation only affected the menu bar.

**Comment by equinusocio** [comment]
> By the way, the reason it crashes is because this key was added (and works) in older versions of MacOS, where the variation only affected the menu bar.

Ah yes, i remember. I did not even notice that with Mojave apple completely replaced it (that makes sense) with the full dark mode.

You are the best :) and i really like your OSS contribution (i know what it means when you already have a job) and if sometime you need help with HTML/CSS and a bit of design let me know.
